<?php
/** @var $block Magento\Customer\Block\Form\Edit */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$customAttributeText = $block->getCustomer()->getCustomAttribute('sample_text_attribute');
$customAttributeYesNo = $block->getCustomer()->getCustomAttribute('sample_yes_no_attribute');
$customAttributeYesNoCheckbox = $block->getCustomer()->getCustomAttribute('sample_yes_no_checkbox');
$customAttributeSelect = $block->getCustomer()->getCustomAttribute('sample_select_attribute');
$_sampleSelectOptions = $this->helper(Hhennes\CustomerAttributes\Helper\Data::class)->getSelectOptions('sample_select_attribute');
$customAttributeFile = $block->getCustomer()->getCustomAttribute('sample_file_attribute');
$customAttributeImage = $block->getCustomer()->getCustomAttribute('sample_image_attribute');
?>
<fieldset class="fieldset">
    <!-- Text Field -->
    <div class="field">
        <label for="sample_text_attribute" class="label"><?= __('sample Text attribute'); ?></label>
        <input type="text" name="sample_text_attribute" id="sample_text_attribute"
               value="<?= ($customAttributeText) ? $customAttributeText->getValue() : '' ?>" class="input-text"/>
    </div>
    <!-- Yes / No field ( select ) @todo check if helper exists -->
    <div class="field">
        <label for="sample_yes_no_attribute" class="label"><?= __('sample yes/no attribute'); ?></label>
        <select name="sample_yes_no_attribute" id="sample_text_attribute">
            <option
                value="0" <?php if (!$customAttributeYesNo || ($customAttributeYesNo && $customAttributeYesNo->getValue()) == 0): ?> selected="selected"<?php endif ?>><?= __('No'); ?></option>
            <option
                value="1" <?php if ($customAttributeYesNo && $customAttributeYesNo->getValue() == 1): ?> selected="selected"<?php endif ?>><?= __('Yes'); ?></option>
        </select>
    </div>
    <!-- Yes / No field ( checkbox with js behaviour ) -->
    <div class="field">
        <label for="sample_yes_no_checkbox_choice" class="label"><?= __('sample yes/no attribute checkbox'); ?></label>
        <input type="checkbox" name="sample_yes_no_checkbox_choice" id="sample_yes_no_checkbox_choice"
               <?php if ($customAttributeYesNoCheckbox && $customAttributeYesNoCheckbox->getValue() == 1): ?> checked="checked"<?php endif;?>
         />
        <input type="hidden" name="sample_yes_no_checkbox" id="sample_yes_no_checkbox"
               value="<?=($customAttributeYesNoCheckbox && $customAttributeYesNoCheckbox->getValue() == 1) ? 1 : 0 ;?>"
        />
    </div>
    <?php
    //Magento 2.4 secure inline js
    $scriptString = <<<script
    require([
        "jquery",
        "mage/mage"
    ], function($){
       console.log('it works secured !');
        var sampleYesNoCheckBoxChoice = $('#sample_yes_no_checkbox_choice');
        var sampleYesNoCheckBoxField = $('#sample_yes_no_checkbox');
        console.log(sampleYesNoCheckBoxChoice);
        $(sampleYesNoCheckBoxChoice).on('change',function(){
            var sampleYesNoValue = ( $(this).is(':checked') ) ? 1 : 0 ;
            console.log('sampleYesNoValue',sampleYesNoValue);
            $(sampleYesNoCheckBoxField).val(sampleYesNoValue);
        });

        });
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

    <!-- Select field -->
    <div class="field">
        <label class="label" for="sample_select_attribute"><span><?= __('sample select attribute') ?></span></label>
        <select name="sample_select_attribute" title="<?= __('sample select attribute') ?>">
            <option value=""><?= __('Please select an option'); ?></option>
            <?php foreach ($_sampleSelectOptions as $option) : ?>
                <option
                    value="<?= $block->escapeHtmlAttr($option['value']) ?>" <?php if ($customAttributeSelect && $customAttributeSelect->getValue() == $option['value']): ?> selected="selected"<?php endif ?>><?= $block->escapeHtml($option['label']->getText()) ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <!-- File field -->
    <div class="field">
        <label class="label" for="sample_file_attribute"><span><?= __('sample file attribute') ?></span></label>
        <input type="file" name="sample_file_attribute" id="sample_file_attribute">
        <?php if (($customAttributeFile)) : ?>
            <p><?= $customAttributeFile->getValue() ?></p>
        <?php endif; ?>
    </div>

    <!-- Image field -->
    <div class="field">
        <label class="label" for="sample_image_attribute"><span><?= __('sample image attribute') ?></span></label>
        <input type="file" name="sample_image_attribute" id="sample_image_attribute">
        <?php if (($customAttributeImage)) : ?>
            <p><?= $customAttributeImage->getValue() ?></p>
            <img src="<?= $this->helper(Hhennes\CustomerAttributes\Helper\Data::class)
                ->getCustomerImageUrl($customAttributeImage->getValue()); ?>"/>
        <?php endif; ?>
    </div>
</fieldset>
