<?php
/** @var $block Magento\Framework\View\Element\Template */
?>
<fieldset class="fieldset">
    <legend class="legend"><?= __('Sample Extensions Attributes'); ?></legend>
    <div class="field ">
        <label for="customer_code" class="label"><?= __('Customer code'); ?></label>
        <input type="text" name="customer_code" id="customer_code" class="input-text"/>
    </div>
    <div class="field ">
        <label for="customer_code" class="label"><?= __('Customer code'); ?></label>
        <input type="text" name="customer_code" id="customer_code" class="input-text"/>
    </div>
</fieldset>
